version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    allow:
      - dependency-name: "remixicon"
    ignore:
      - dependency-name: "remixicon"
        update-types: ["version-update:semver-patch"]
    assignees:
      - "zaniluca"
