name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    # Only publish on master branch
    if: endsWith(github.ref, 'master')
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-path.outputs.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: publish
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="@zaniluca/react-remixicon@${{ github.ref }}" \
              --generate-notes
